on: [push, pull_request]
name: ci
jobs:
  linux-ci:
    name: linux-${{ matrix.name }}
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: gcc
            bazel: --config gcc
            cc: gcc-10
            cxx: g++-10

          - name: clang-10
            bazel: --config clang
            cc: clang-10
            cxx: clang++-10

          - name: clang-12
            bazel: --config clang
            cc: clang-12
            cxx: clang++-12
            apt: clang-12

          - name: clang-asan
            bazel: --config clang --config asan
            cc: clang-12
            cxx: clang++-12
            apt: clang-12

          - name: clang-ubsan
            bazel: --config clang --config ubsan
            cc: clang-12
            cxx: clang++-12
            apt: clang-12

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
          sudo apt update
          sudo apt install libxrandr-dev libgl-dev ${{ matrix.apt }}
          echo "CC=${{ matrix.cc }}" >> $GITHUB_ENV
          echo "CXX=${{ matrix.cxx }}" >> $GITHUB_ENV
          wget https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-linux-amd64 --output-document=bazel
    - name: Build
      run: bazel build //... ${{ matrix.bazel }}
    - name: Test
      run: bazel test //... ${{ matrix.bazel }}
    - name: Run
      run: bazel run browser:tui ${{ matrix.bazel }}

  windows-msvc:
    runs-on: windows-2019
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: curl --output bazel.exe https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-windows-amd64.exe
    - name: Build
      run: bazel build ///... --config msvc
    - name: Test
      run: bazel test ///... --config msvc
    - name: Run
      run: bazel run browser:tui --config msvc

  buildifier:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
          wget https://github.com/bazelbuild/buildtools/releases/download/4.0.1/buildifier
          sudo chmod +x buildifier
    - name: Check
      run: ./buildifier --lint=warn --warnings=all -mode diff WORKSPACE $(find . -type f -iname *.BUILD -or -iname BUILD)
