on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [master]
name: ci
jobs:
  linux-ci:
    name: linux-${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: gcc-12
            os: ubuntu-22.04
            compiler: gcc
            version: 12
            bazel: --config gcc12 --run_under="valgrind --leak-check=full --errors-for-leak-kinds=all --error-exitcode=1 --track-origins=yes --show-leak-kinds=all"
            apt: g++-12 valgrind

          - name: clang-14-tsan
            os: ubuntu-22.04
            compiler: clang
            version: 14
            bazel: --config tsan

          - name: clang-asan
            os: ubuntu-22.04
            compiler: clang
            version: 14
            bazel: --config asan

          - name: clang-ubsan
            os: ubuntu-22.04
            compiler: clang
            version: 14
            bazel: --config ubsan

          - name: clang-15
            os: ubuntu-22.04
            compiler: clang
            version: 15
            bazel: --config clang15

          - name: clang-15-libc++
            os: ubuntu-22.04
            compiler: clang
            version: 15
            bazel: --config libc++ --config clang15
            apt: libc++abi-15-dev libc++-15-dev

    steps:
      - name: Prepare clang install
        if: startsWith(matrix.compiler, 'clang') && matrix.version == 15
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-${{ matrix.version }} main"
      - name: Setup gcc
        if: startsWith(matrix.compiler, 'gcc')
        run: |
          echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
      - name: Setup clang
        if: startsWith(matrix.compiler, 'clang')
        run: |
          echo "CC=clang-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX=clang++-${{ matrix.version }}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Install
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends libgl-dev ${{ matrix.compiler }}-${{ matrix.version }} ${{ matrix.apt }}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/bazel
          key: ${{ matrix.name }}-${{ hashFiles('.bazelversion', 'WORKSPACE', 'third_party/**') }}
          restore-keys: ${{ matrix.name }}-
      - name: Build
        run: bazel build //... ${{ matrix.bazel }}
      - name: Test
        run: bazel test //... ${{ matrix.bazel }}
      # TODO(robinlinden): This no longer runs in CI due to http://example.com
      # being inaccessible.
      # - name: Run
      #   run: bazel run browser:tui ${{ matrix.bazel }}

  linux-gcc-10-coverage:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: ~/.cache/bazel
          key: ${{ matrix.name }}-${{ hashFiles('.bazelversion', 'WORKSPACE', 'third_party/**') }}
          restore-keys: ${{ matrix.name }}-
      - name: Install
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends libgl-dev lcov
      - name: Setup
        run: |
          echo "CC=gcc-10" >> $GITHUB_ENV
          echo "CXX=g++-10" >> $GITHUB_ENV
      - name: Coverage
        run: bazel coverage ... --config gcc10
      - name: Summary
        run: lcov --summary bazel-out/_coverage/_coverage_report.dat
      - name: Upload
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -f bazel-out/_coverage/_coverage_report.dat

  windows-msvc:
    runs-on: windows-2022
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.cache/bazel
          key: windows_msvc-${{ hashFiles('WORKSPACE', 'third_party/**') }}
      - run: echo "build --disk_cache ~/.cache/bazel" >.bazelrc.local
      - name: Build
        run: bazel build ... -c dbg
      - name: Test
        run: bazel test ... -c dbg
      # TODO(robinlinden): This no longer runs in CI due to http://example.com
      # being inaccessible.
      # - name: Run
      #   run: bazel run browser:tui -c dbg

  windows-clang-cl:
    runs-on: windows-2022
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.cache/bazel
          key: windows_clang_cl-${{ hashFiles('WORKSPACE', 'third_party/**') }}
      - run: echo "build --config clang-cl" >.bazelrc.local
      - run: echo "build --disk_cache ~/.cache/bazel" >>.bazelrc.local
      - run: bazel test ...
      # TODO(robinlinden): This no longer runs in CI due to http://example.com
      # being inaccessible.
      # - run: bazel run browser:tui

  clang-format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install --no-install-recommends clang-format-14
      - name: Format
        run: find . -name *.h -o -name *.cpp | xargs clang-format-14 -style=file -i
      - name: Check
        run: git diff --exit-code

  buildifier:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: |
          wget --output-document=buildifier https://github.com/bazelbuild/buildtools/releases/download/5.1.0/buildifier-linux-amd64
          sudo chmod +x buildifier
      - name: Check
        run: ./buildifier --lint=warn --warnings=all -mode diff WORKSPACE $(find . -type f -iname "*.BUILD" -or -iname BUILD -or -iname "*.bzl")

  prettier:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: npm install --global prettier@2.7.1
      # Prettier thinks our fragment shaders are JS-something and complains
      # about syntax errors.
      - run: npx prettier --ignore-path .gitignore --write . '!**/*.frag'
      - run: git diff --exit-code

  shfmt:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: pip install shfmt-py==3.4.3.1
      - run: shfmt -i 2 -w $(shfmt -f .)
      - run: git diff --exit-code

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
